name: CI

on:
  push:
    branches:
    - main

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - run: npm install
    - name: Execute script.js
      run: node src/scripts/angular-env-file-creator.js
      env:
        PROD_ENV_CONFIG: ${{ secrets.PROD_ENV_CONFIG }}
    - run: npm run prod
    - name: Deploy to Firebase
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > "$HOME"/gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcp-key.json
        npm install -g firebase-tools
        firebase deploy --only hosting
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
